Fix the build of tests on MinGW
Currently the tests are failing to build with "undefined reference to
`_imp__htonl@4'". The fix is to add the platform_deps to tests
dependencies. Do that by adding it to the libsoup_dep thus all the
targets are fixed.

https://gitlab.gnome.org/GNOME/libsoup/merge_requests/60